version: '3.8'
services:
  backend:
    build:
      context: ./backend/src
    networks:
      - web_net
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/csv-data:/backend/csv-data
    mem_limit: 25g


  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    image: "postgres:latest"
    networks:
      - web_net
    volumes:
      - ./backend/data:/var/lib/postgresql/data
      - ./backend/csv-data:/var/lib/postgresql/csv-data
    ports:
      - "5432:5432"
    expose:
      - "5432"

networks:
  web_net:
    driver: bridge